# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(71, b'vtc - Vertcoin'), (0, b'btc - Bitcoin'), (48, b'ltc - Litecoin'), (55, b'ppc - Peercoin'), (30, b'doge - Dogecoin'), (50, b'myr - MyriadCoin'), (76, b'dash - Dash')])),
                ('deposit_skip', models.IntegerField(default=0)),
                ('change_skip', models.IntegerField(default=0)),
            ],
        ),
    ]
