# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20160619_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangecurrency',
            name='id',
        ),
        migrations.AlterField(
            model_name='exchangecurrency',
            name='currency',
            field=models.IntegerField(choices=[(2147483676, b'vtc - Vertcoin'), (2147483648, b'btc - Bitcoin'), (2147483650, b'ltc - Litecoin'), (2147483654, b'ppc - Peercoin'), (2147483651, b'doge - Dogecoin'), (2147483738, b'myr - MyriadCoin'), (2147483653, b'dash - Dash')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exchangemasterkey',
            name='utxos',
            field=models.TextField(blank=True),
        ),
    ]
