# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20160619_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangecurrency',
            name='change_skip',
        ),
        migrations.RemoveField(
            model_name='exchangecurrency',
            name='deposit_skip',
        ),
        migrations.AddField(
            model_name='exchangecurrency',
            name='max_fiat_currency',
            field=models.CharField(choices=[(b'usd', b'USD'), (b'eur', b'EUR'), (b'cny', b'CNY'), (b'jpy', b'JPY')], default=b'usd', max_length=4),
        ),
        migrations.AddField(
            model_name='exchangecurrency',
            name='max_fiat_deposit',
            field=models.FloatField(default=10),
        ),
    ]
