# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20160619_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeCurrency')),
                ('master_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeMasterKey')),
            ],
        ),
    ]
