# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_manualdeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeaddress',
            name='exchange_rate',
            field=models.FloatField(null=True),
        ),
    ]
