# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20160620_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeaddress',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exchangecurrency',
            name='currency',
            field=models.IntegerField(choices=[(2147483676, b'vtc - Vertcoin'), (2147483648, b'btc - Bitcoin'), (2147483650, b'ltc - Litecoin'), (2147483740, b'uno - Unobtanium'), (2147483651, b'doge - Dogecoin'), (2147483738, b'myr - MyriadCoin'), (2147483653, b'dash - Dash')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exchangecurrency',
            name='max_fiat_currency',
            field=models.CharField(choices=[(b'usd', b'USD'), (b'eur', b'EUR'), (b'cny', b'CNY')], default=b'usd', max_length=4),
        ),
        migrations.AlterField(
            model_name='exchangemasterkey',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
