# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20170207_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangecurrency',
            name='currency',
            field=models.IntegerField(choices=[(2147483648, b'btc - Bitcoin'), (2147483656, b'ftc - Feathercoin'), (2147483650, b'ltc - Litecoin'), (2147483740, b'uno - Unobtanium'), (2147483651, b'doge - Dogecoin'), (2147483738, b'myr - MyriadCoin'), (2147483653, b'dash - Dash'), (143, b'ric - Riecoin')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exchangecurrency',
            name='max_fiat_currency',
            field=models.CharField(choices=[(b'usd', b'USD'), (b'eur', b'EUR'), (b'cny', b'CNY'), (b'jpy', b'JPY')], default=b'usd', max_length=4),
        ),
    ]
