# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20170503_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangecurrency',
            name='currency',
            field=models.IntegerField(choices=[(2147483781, b'zec - ZCash'), (2147483757, b'ptc - Pesetacoin'), (2147483653, b'dash - Dash'), (2147483648, b'btc - Bitcoin Legacy'), (2147483791, b'ric - Riecoin'), (2147483651, b'doge - Dogecoin'), (2147483656, b'ftc - Feathercoin'), (2147483738, b'xmy - MyriadCoin'), (2147483755, b'mars - MarsCoin'), (2147483793, b'bch - Bitcoin Cash'), (2147483775, b'leo - LEOcoin'), (2147483665, b'grs - Groestlcoin'), (2147483670, b'mona - MonaCoin'), (2147483723, b'fjc - FujiCoin'), (2147483650, b'ltc - Litecoin'), (2147483740, b'uno - Unobtanium')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exchangecurrency',
            name='max_fiat_currency',
            field=models.CharField(choices=[(b'usd', b'USD'), (b'eur', b'EUR'), (b'cny', b'CNY'), (b'jpy', b'JPY'), (b'idr', b'IDR'), (b'cad', b'CAD'), (b'gbp', b'GBP')], default=b'usd', max_length=4),
        ),
    ]
