# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedTransaction',
            fields=[
                ('txid', models.CharField(max_length=72, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
