# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiexplorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedtransaction',
            name='crypto',
            field=models.CharField(default=b'btc', max_length=8),
        ),
    ]
