# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiexplorer', '0002_cachedtransaction_crypto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_text', models.TextField()),
                ('pubkey', models.TextField()),
                ('txid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiexplorer.CachedTransaction')),
            ],
        ),
    ]
