# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiexplorer', '0003_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='crypto',
            field=models.CharField(default=b'btc', max_length=8),
        ),
        migrations.AlterField(
            model_name='memo',
            name='txid',
            field=models.CharField(db_index=True, max_length=72),
        ),
    ]
