# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multiexplorer', '0005_memo_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pulled', models.DateTimeField(default=django.utils.timezone.now)),
                ('pull_url', models.TextField()),
            ],
        ),
    ]
