# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multiexplorer', '0006_pullhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pushed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='memo',
            name='signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
