# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multiexplorer', '0007_auto_20170211_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedtransaction',
            name='date_fetched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cachedtransaction',
            name='service_used',
            field=models.TextField(default=b''),
        ),
    ]
