# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiexplorer', '0009_iptracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptracker',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
