# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_services', models.TextField()),
                ('network_results', models.TextField()),
                ('offending_type', models.CharField(max_length=32)),
                ('offending_value', models.TextField()),
                ('offending_currency', models.CharField(max_length=6)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
