# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmasterkeys',
            name='encrypted_seed',
            field=models.CharField(max_length=172),
        ),
    ]
