# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20160418_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletmasterkeys',
            old_name='encrypted_seed',
            new_name='encrypted_mnemonic',
        ),
    ]
