# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_cachedtransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedTransaction',
        ),
    ]
