# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_delete_cachedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmasterkeys',
            name='auto_logout',
            field=models.IntegerField(choices=[(5, b'5 minutes of inactivity'), (30, b'30 minutes of inactivity'), (0, b'Never')], default=0),
        ),
        migrations.AddField(
            model_name='walletmasterkeys',
            name='display_fiat',
            field=models.CharField(default=b'usd', max_length=5),
        ),
        migrations.AddField(
            model_name='walletmasterkeys',
            name='show_wallet_list',
            field=models.TextField(default=b'btc,ltc,doge'),
        ),
    ]
