# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20160429_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmasterkeys',
            name='show_wallet_list',
            field=models.TextField(default=b'btc,ltc,doge,dash'),
        ),
    ]
