# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20160604_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
